namespace Amadevus.RecordGenerator
{
    internal static class RecordPartial
    {

        public const string FileHeader = "// Record partial generated by RecordGenerator";

        public const string FilenamePostfix = "RecordGenerator";

    }
}