namespace Amadevus.RecordGenerator
{
    /// <summary>
    /// Identifies class or struct that is supposed to have a partial with ctor and mutators generated by source generator.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("RecordGenerator", "0.0.1")]
    [System.Diagnostics.Conditional("NEVER")]
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
    internal sealed class RecordAttribute : System.Attribute
    {
        public RecordAttribute()
        {
        }


        public string PrimaryCtorAccess { get; set; } = "public";

        /// <summary>
        /// Gets or sets whether mutator methods should be generated (e.g. WithSurname). Default is true.
        /// </summary>
        public bool GenerateMutators { get; set; } = true;


        /// <summary>
        /// Gets or sets whether collection mutator methods should be generated (e.g. AddItems, ReplaceItems). Default is true.
        /// </summary>
        public bool GenerateCollectionMutators { get; set; } = true;
    }
}
