using Microsoft.CodeAnalysis.CodeFixes;
using Microsoft.CodeAnalysis.Diagnostics;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TestHelper;
using Xunit;

namespace Amadevus.RecordGenerator.Test
{
    public class RecordPartialInvalidTest : GeneratorCodeFixVerifier
    {
        [Theory]
        [ClassData(typeof(TestCases))]
        public void Given_Source_Then_Verify_Diagnostic_And_Codefix(
            string description, GeneratorSourcePackage sourcePackage, DiagnosticResult[] diagnosticResults)
        {
            VerifyCSharpDiagnostic(sourcePackage.GetInputSources(), diagnosticResults);
            VerifyCSharpGeneratorFix(sourcePackage);
        }

        protected override CodeFixProvider GetCSharpCodeFixProvider()
        {
            return new GenerateRecordPartialCodeFixProvider();
        }

        protected override DiagnosticAnalyzer GetCSharpDiagnosticAnalyzer()
        {
            return new RecordGeneratorAnalyzer();
        }

        private class TestCases : TheoryDataProvider
        {
            public override IEnumerable<ITheoryDatum> GetDataSets()
            {
                const string @namespace = "RecordGeneratorTests";
                const string typeName = "Person";
                yield return new GeneratorTheoryData
                {
                    Description = "new string property",
                    SourcePackage = new GeneratorSourcePackage
                    {
                        OldSource = @"
namespace RecordGeneratorTests
{
    [Record]
    partial class Person
    {
        public string FirstName { get; }

        public string LastName { get; }
    }
}",
                        AdditionalSources = new[]
                        {
                            GenerateRecordAttributeDeclarationCodeFixProvider.RecordAttributeDeclarationSource(@namespace),
                            @"// Record partial generated by RecordGenerator
// WARNING any changes made to this file will be lost when generator is run again

namespace RecordGeneratorTests
{
    [System.CodeDom.Compiler.GeneratedCode(""RecordGenerator"", ""GENERATOR_VERSION"")]
    partial class Person
    {
        public Person(string FirstName)
        {
            this.FirstName = FirstName;
        }

        public Person WithFirstName(string FirstName)
        {
            return new Person
(FirstName);
        }
    }
}".ReplaceRecordGeneratorVersion(Properties.VersionString)
                        },
                        ChangedSource = @"// Record partial generated by RecordGenerator
// WARNING any changes made to this file will be lost when generator is run again

namespace RecordGeneratorTests
{
    [System.CodeDom.Compiler.GeneratedCode(""RecordGenerator"", ""GENERATOR_VERSION"")]
    partial class Person
    {
        public Person(string FirstName, string LastName)
        {
            this.FirstName = FirstName;
            this.LastName = LastName;
        }

        public Person WithFirstName(string FirstName)
        {
            return new Person
(FirstName, LastName);
        }

        public Person WithLastName(string LastName)
        {
            return new Person
(FirstName, LastName);
        }
    }
}".ReplaceRecordGeneratorVersion(Properties.VersionString)
                    }.AndFixedSameAsOld(),
                    ExpectedDiagnostics = new[]
                    {
                        new DiagnosticResult(RecordPartialInvalidDiagnostic.Descriptor, typeName)
                        {
                            Locations =
                            new[] {
                                new DiagnosticResultLocation("Test0.cs", 5, 19)
                            }
                        }
                    }
                };
                yield return new GeneratorTheoryData
                {
                    Description = "renamed property",
                    SourcePackage = new GeneratorSourcePackage
                    {
                        OldSource = @"
namespace RecordGeneratorTests
{
    [Record]
    partial class Person
    {
        public string FirstName { get; }

        public string LastName { get; }
    }
}",
                        AdditionalSources = new[]
                        {
                            GenerateRecordAttributeDeclarationCodeFixProvider.RecordAttributeDeclarationSource(@namespace),
                            @"// Record partial generated by RecordGenerator
// WARNING any changes made to this file will be lost when generator is run again

namespace RecordGeneratorTests
{
    [System.CodeDom.Compiler.GeneratedCode(""RecordGenerator"", ""GENERATOR_VERSION"")]
    partial class Person
    {
        public Person(string FirstName, string SecondName)
        {
            this.FirstName = FirstName;
            this.SecondName = SecondName;
        }

        public Person WithFirstName(string FirstName)
        {
            return new Person
(FirstName, SecondName);
        }

        public Person WithSecondName(string SecondName)
        {
            return new Person
(FirstName, SecondName);
    }
}".ReplaceRecordGeneratorVersion(Properties.VersionString)
                        },
                        ChangedSource = @"// Record partial generated by RecordGenerator
// WARNING any changes made to this file will be lost when generator is run again

namespace RecordGeneratorTests
{
    [System.CodeDom.Compiler.GeneratedCode(""RecordGenerator"", ""GENERATOR_VERSION"")]
    partial class Person
    {
        public Person(string FirstName, string LastName)
        {
            this.FirstName = FirstName;
            this.LastName = LastName;
        }

        public Person WithFirstName(string FirstName)
        {
            return new Person
(FirstName, LastName);
        }

        public Person WithLastName(string LastName)
        {
            return new Person
(FirstName, LastName);
        }
    }
}".ReplaceRecordGeneratorVersion(Properties.VersionString)
                    }.AndFixedSameAsOld(),
                    ExpectedDiagnostics = new[]
                    {
                        new DiagnosticResult(RecordPartialInvalidDiagnostic.Descriptor, typeName)
                        {
                            Locations =
                            new[] {
                                new DiagnosticResultLocation("Test0.cs", 5, 19)
                            }
                        }
                    }
                };
                yield return new GeneratorTheoryData
                {
                    Description = "removed property",
                    SourcePackage = new GeneratorSourcePackage
                    {
                        OldSource = @"
namespace RecordGeneratorTests
{
    [Record]
    partial class Person
    {
        public string FirstName { get; }
    }
}",
                        AdditionalSources = new[]
                        {
                            GenerateRecordAttributeDeclarationCodeFixProvider.RecordAttributeDeclarationSource(@namespace),
                            @"// Record partial generated by RecordGenerator
// WARNING any changes made to this file will be lost when generator is run again

namespace RecordGeneratorTests
{
    [System.CodeDom.Compiler.GeneratedCode(""RecordGenerator"", ""GENERATOR_VERSION"")]
    partial class Person
    {
        public Person(string FirstName, string SecondName)
        {
            this.FirstName = FirstName;
            this.SecondName = SecondName;
        }

        public Person WithFirstName(string FirstName)
        {
            return new Person
(FirstName, SecondName);
        }

        public Person WithSecondName(string SecondName)
        {
            return new Person
(FirstName, SecondName);
    }
}".ReplaceRecordGeneratorVersion(Properties.VersionString)
                        },
                        ChangedSource = @"// Record partial generated by RecordGenerator
// WARNING any changes made to this file will be lost when generator is run again

namespace RecordGeneratorTests
{
    [System.CodeDom.Compiler.GeneratedCode(""RecordGenerator"", ""GENERATOR_VERSION"")]
    partial class Person
    {
        public Person(string FirstName)
        {
            this.FirstName = FirstName;
        }

        public Person WithFirstName(string FirstName)
        {
            return new Person
(FirstName);
        }
    }
}".ReplaceRecordGeneratorVersion(Properties.VersionString)
                    }.AndFixedSameAsOld(),
                    ExpectedDiagnostics = new[]
                    {
                        new DiagnosticResult(RecordPartialInvalidDiagnostic.Descriptor, typeName)
                        {
                            Locations =
                            new[] {
                                new DiagnosticResultLocation("Test0.cs", 5, 19)
                            }
                        }
                    }
                };
                yield return new GeneratorTheoryData
                {
                    Description = "property type changed",
                    SourcePackage = new GeneratorSourcePackage
                    {
                        OldSource = @"
namespace RecordGeneratorTests
{
    [Record]
    partial class Person
    {
        public string FirstName { get; }

        public int LastName { get; }
    }
}",
                        AdditionalSources = new[]
                        {
                            GenerateRecordAttributeDeclarationCodeFixProvider.RecordAttributeDeclarationSource(@namespace),
                            @"// Record partial generated by RecordGenerator
// WARNING any changes made to this file will be lost when generator is run again

namespace RecordGeneratorTests
{
    [System.CodeDom.Compiler.GeneratedCode(""RecordGenerator"", ""GENERATOR_VERSION"")]
    partial class Person
    {
        public Person(string FirstName, string LastName)
        {
            this.FirstName = FirstName;
            this.LastName = LastName;
        }

        public Person WithFirstName(string FirstName)
        {
            return new Person
(FirstName, LastName);
        }

        public Person WithLastName(string LastName)
        {
            return new Person
(FirstName, LastName);
    }
}".ReplaceRecordGeneratorVersion(Properties.VersionString)
                        },
                        ChangedSource = @"// Record partial generated by RecordGenerator
// WARNING any changes made to this file will be lost when generator is run again

namespace RecordGeneratorTests
{
    [System.CodeDom.Compiler.GeneratedCode(""RecordGenerator"", ""GENERATOR_VERSION"")]
    partial class Person
    {
        public Person(string FirstName, int LastName)
        {
            this.FirstName = FirstName;
            this.LastName = LastName;
        }

        public Person WithFirstName(string FirstName)
        {
            return new Person
(FirstName, LastName);
        }

        public Person WithLastName(int LastName)
        {
            return new Person
(FirstName, LastName);
        }
    }
}".ReplaceRecordGeneratorVersion(Properties.VersionString)
                    }.AndFixedSameAsOld(),
                    ExpectedDiagnostics = new[]
                    {
                        new DiagnosticResult(RecordPartialInvalidDiagnostic.Descriptor, typeName)
                        {
                            Locations =
                            new[] {
                                new DiagnosticResultLocation("Test0.cs", 5, 19)
                            }
                        }
                    }
                };
            }
        }

        public class GeneratorTheoryData : ITheoryDatum
        {
            public string Description { get; set; }

            public GeneratorSourcePackage SourcePackage { get; set; }

            public DiagnosticResult[] ExpectedDiagnostics { get; set; }

            public object[] ToParameterArray()
            {
                return
                    new object[]
                    {
                        Description,
                        SourcePackage,
                        ExpectedDiagnostics
                    };
            }
        }
    }
}
