namespace Amadevus.RecordGenerator.Analyzers
{
    internal static class RecordPartialProperties
    {
        public const string FileHeader = "// Record partial generated by RecordGenerator";

        public const string FilenamePostfix = "RecordGenerator";

        public const string FilePostheaderWarning = "// WARNING any changes made to this file will be lost when generator is run again";
    }
}